# Generated by Django 4.1.12 on 2023-10-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_lancer_bio_alter_lancer_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pow',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
