# Generated by Django 4.1.12 on 2023-10-28 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_lancer_password_userprofile_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lancer',
            old_name='firt_name',
            new_name='first_name',
        ),
    ]
